### ISSUE TITLE
Angular visibility

### ISSUE THREAD

**Issue by pastinepolenta** [mattslocum/ng-webworker#7]
I have this function

```
function prepareTrees(){
    angular.forEach
    ...
```

then I call it with a web worker

```
var prepareTreesWorker = Webworker.create(prepareTrees);
prepareTreesWorker.run().then(function(result) {
     console.log("Trees are prepared");
});
```

I get an error `angular` is not defined. How can we pass angular reference inside the worker ?

**Comment by pastinepolenta** [comment]
OK I think this explains why http://kindofcode.com/web-workers-in-angular/

**Comment by mattslocum** [comment]
Correct. I created ng-webworker to yank code out of your existing file. The confusing thing is to remember that the webworker does not share lexical scope. Try to think of webworkers not as multi-threading, but more as multi-process in that it doesn't share resources. I should make some drawings on my site like that one did. http://glebbahmutov.com/blog/web-working-like-a-boss/ did a good write up on it.

If you are using an array, I'd recommend using the JS native forEach instead of the angular one anyway. 

It is also possible to import angular into your web-worker, but that would be extremely overkill for your worker since angular is a ui frameworks and a web-worker doesn't have any ui. You can import libraries using importScripts. There is an example at the bottom of http://mattslocum.github.io/ng-webworker/demo/

**Comment by wiadev** [comment]
@mattslocum Thanks for the great library.
I'm going to use your library in my ionic v1 project.
Can I use the angular service which I defined and other bower libraries (e.g. lodash)?
