### ISSUE TITLE
How to get the location and the navigator global variables ?

### ISSUE THREAD

**Issue by ronycohen** [mattslocum/ng-webworker#8]
Hello, 

Thank you for your work !
Can you please tell me how to get the location and the navigator global variables ?

I'm unable to call a local file with importScripts, as I'm unable to know the location.pathname....

Thank you for your answer.

**Comment by mattslocum** [comment]
Web-workers are their own thread. Your function gets ripped out and given a new lexical scope in a blob. It no longer knows where it came from. This is just how browsers work and it is probably considered a security feature. Here's a list of supported globals, but beware as some are not supported by all browsers. https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope

I'd recommend passing any needed data into the web-worker, when you call run(). Check out the demo http://mattslocum.github.io/ng-webworker/demo/

I'm going to close this since it isn't a bug/issue, but feel free to comment back if needed.

**Comment by ronycohen** [comment]
Thank you @mattslocum for this quick answer!

Maybe I didn't explained very well what I tried to achieve : 

``` javascript
            importScripts("https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.20/require.min.js");
            //importScripts("lib/requireJS/require.min.js");  // NOT WORKING
            require(['https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.0/lodash.min.js'], function(_) {.....
            //require(['../lib/lodash/lodash.min.js'], function(_) {............  // NOT WORKING
```

I just wanna access to local js files :)

**Comment by ronycohen** [comment]
I'm using Ionic Framework with ng-webworker, and I'd like to have a "offline first" app.

**Comment by ronycohen** [comment]
I ended using :  require(['http://localhost:8100/lib/lodash/lodash.js'], function(_) {

it works properly.

**Comment by mattslocum** [comment]
Yeah. A relative path probably wont work since the web-working lives in a blob and there is probably nothing relative to it. You should try to convert the relative path into an absolute path. I've used this in the past: http://www.joezimjs.com/javascript/the-lazy-mans-url-parsing/

**Comment by ronycohen** [comment]
Ok thank you very much
